# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_trip_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
