# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20171215_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='travels.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='users_joined',
            field=models.ManyToManyField(related_name='users_trips', to='travels.User'),
        ),
    ]
